MODEL:
    NUM_CLASSES: 5
    THRESHOLD: 0.4
    BACKBONE:
        NAME: 'basic'
        PRETRAINED: True
        OUT_CHANNELS: [128, 256, 512, 256, 128, 64]
        INPUT_CHANNELS: 3
    PRIORS:
        FEATURE_MAPS: [[75, 75], [38, 38], [19, 19], [10, 10], [5, 5], [2, 2]]#, [1, 1]]
        STRIDES: [[8, 8], [16, 16], [32, 32], [64, 64], [128, 128], [300, 300]]
        MIN_SIZES: [[30, 30], [60, 60], [111, 111], [162, 162], [213, 213], [264, 264]]
        MAX_SIZES: [[60, 60], [111, 111], [162, 162], [213, 213], [264, 264], [315, 315]]
        ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2], [2]]
        BOXES_PER_LOCATION: [4, 6, 6, 6, 4, 4]
INPUT:
    IMAGE_SIZE: [600, 600]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    MAX_ITER: 120000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
OUTPUT_DIR: 'outputs/rdd2020'
DATASET_DIR: "datasets"
EVAL_STEP: 5000
TEST:
    CONFIDENCE_THRESHOLD: 0.05